# Generated by Django 4.2.5 on 2023-10-21 13:05

from django.db import migrations, models
import my_work.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0002_project_thumb_1024_project_thumb_2048_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to=my_work.models.upload_to_original),
        ),
    ]
