# Generated by Django 4.2.5 on 2023-10-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.CharField(blank=True, help_text='année de création', max_length=4, verbose_name='créé en'),
        ),
    ]
