# Generated by Django 4.2.5 on 2023-10-22 12:59

from django.db import migrations, models
import my_work.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0004_project_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', help_text='Ex : 1905x1177. Soit largeur divisé par 1.618', upload_to=my_work.models.upload_to_original),
        ),
    ]
