# Generated by Django 5.0.9 on 2024-12-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_formpage_image_formpage_hero_image'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormPage',
            new_name='ContactPage',
        ),
    ]
