# Generated by Django 5.0.9 on 2024-12-21 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogindexpage_image'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='image',
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
