# Generated by Django 5.0.9 on 2024-12-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_blogindexpage_image_blogindexpage_hero_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='image',
            new_name='hero_image',
        ),
    ]
