# Generated by Django 5.0.9 on 2024-11-09 15:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
