# Generated by Django 5.0.9 on 2024-11-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='title_intro',
            field=models.CharField(blank=True, max_length=50, verbose_name="titre de l'intro"),
        ),
    ]
