# Generated by Django 5.0.9 on 2024-11-11 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutpage_title_intro'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Image à propos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
