# Generated by Django 5.0.9 on 2024-12-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_remove_aboutpage_image_aboutpage_image_banner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='image_banner',
            new_name='hero_image',
        ),
    ]
