# Generated by Django 5.0.9 on 2024-11-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='link',
            field=models.URLField(blank=True, max_length=255, verbose_name='lien du projet'),
        ),
    ]
