# Generated by Django 5.0.9 on 2024-11-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codepen_url', models.URLField(blank=True, verbose_name='Codepen URL')),
                ('discord_url', models.URLField(blank=True, verbose_name='Discord URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('mastodon_url', models.URLField(blank=True, verbose_name='Mastodon URL')),
                ('pinterest_url', models.URLField(blank=True, verbose_name='Pinterest URL')),
                ('snapchat_url', models.URLField(blank=True, verbose_name='Snapchat URL')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram URL')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok URL')),
                ('twitch_url', models.URLField(blank=True, verbose_name='Twitch URL')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='WhatsApp URL')),
                ('x_url', models.URLField(blank=True, verbose_name='X URL (ex twitter)')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Youtube URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
