# Generated by Django 5.0.9 on 2024-11-01 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialsettings',
            options={'verbose_name': 'Paramètres des réseaux sociaux'},
        ),
    ]
