# Generated by Django 5.0.9 on 2024-11-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_myprofilesettings_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofilesettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, verbose_name='numéro de téléphone'),
        ),
    ]
