# Generated by Django 5.0.9 on 2024-11-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_myprofilesettings_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofilesettings',
            name='city',
            field=models.CharField(blank=True, max_length=254, verbose_name='ville'),
        ),
    ]
