# Generated by Django 5.0.9 on 2024-11-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Compétence et savoir-faire', 'verbose_name_plural': 'Compétences et savoir-faire'},
        ),
    ]
