# Generated by Django 5.0.9 on 2024-11-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_skills_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='titre')),
                ('icon', models.CharField(blank=True, help_text="Renseigner le nom de l'icône. (Voir sur Devicon)", max_length=150, verbose_name='icône')),
            ],
            options={
                'verbose_name': 'Outil de développement',
                'verbose_name_plural': 'Outils de développement',
            },
        ),
    ]
