# Generated by Django 5.0.9 on 2024-11-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='titre')),
            ],
            options={
                'verbose_name': "Centre d'intérêt",
                'verbose_name_plural': "Centres d'intérêts",
            },
        ),
    ]
