# Generated by Django 5.0.9 on 2024-12-17 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_image_default_imagedefault_image'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='background_color',
            field=models.CharField(default='', help_text='Format Hexadécimal #f20000', max_length=7),
        ),
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Page image Banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
