# Generated by Django 5.0.9 on 2024-11-09 09:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resumepage_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepage',
            name='education',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('block_quote', 9), ('embed_block', 10), ('code_block', 13), ('education', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Choisir la taille du titre'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'code', 'superscript', 'subscript', 'strikethrough'], 'icon': 'pilcrow', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('text', 7), ('attribute_name', 8)]], {}), 10: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media', 'template': 'blocks/embed_block.html'}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('django', 'Django/Jinja2'), ('docker', 'Docker'), ('git', 'Git'), ('html', 'HTML'), ('http', 'HTTP'), ('icon', 'Icon'), ('ini', 'Ini'), ('java', 'Java'), ('javascript', 'Javascript'), ('json', 'JSON'), ('markdown', 'Markdown'), ('php', 'PHP'), ('python', 'Python'), ('regex', 'Regex'), ('ruby', 'Ruby'), ('sass', 'Sass (Sass)'), ('scss', 'Sass (Scss)'), ('sql', 'SQL'), ('stylus', 'Stylus'), ('swift', 'Swift'), ('twig', 'Twig'), ('typescript', 'TypeScript'), ('vim', 'vim'), ('visual-basic', 'Visual Basic'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 12: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 13: ('wagtail.blocks.StructBlock', [[('language', 11), ('code', 12)]], {'label': 'Code'}), 14: ('wagtail.blocks.CharBlock', (), {'form_classname': 'school', 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'form_classname': 'city', 'required': True}), 16: ('wagtail.blocks.DateBlock', (), {}), 17: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a level'), ('cap', 'CAP'), ('bep', 'BEP'), ('bac', 'BAC'), ('bac+2', 'BAC+2'), ('bac+3', 'BAC+3'), ('bac+4', 'BAC+4'), ('bac+5', 'BAC+5'), ('bac+8', 'BAC+8')], 'required': False}), 18: ('wagtail.blocks.BooleanBlock', (), {}), 19: ('wagtail.blocks.StructBlock', [[('title', 0), ('school', 14), ('city', 15), ('date_start', 16), ('date_end', 16), ('level', 17), ('certificate', 18), ('description', 3)]], {'group': 'Sections'})}, verbose_name='Bloc de formation'),
        ),
    ]
