# Generated by Django 5.0.9 on 2024-11-09 15:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_resumepage_experience_alter_resumepage_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepage',
            name='education',
            field=wagtail.fields.StreamField([('education_block', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Titre', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'school', 'label': 'Ecole', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'city', 'label': 'Ville', 'required': True}), 3: ('wagtail.blocks.DateBlock', (), {'label': 'Date de début'}), 4: ('wagtail.blocks.DateBlock', (), {'label': 'Date de fin', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Selectionnez un niveau'), ('cap', 'CAP'), ('bep', 'BEP'), ('bac', 'BAC'), ('bac+2', 'BAC+2'), ('bac+3', 'BAC+3'), ('bac+4', 'BAC+4'), ('bac+5', 'BAC+5'), ('bac+8', 'BAC+8')], 'label': 'Niveau', 'required': False}), 6: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'cocher la case si le diplôme a été obtenu', 'label': 'Diplôme', 'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'code', 'superscript', 'subscript', 'strikethrough'], 'icon': 'pilcrow', 'label': 'Description', 'required': False, 'template': 'blocks/paragraph_block.html'}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('school', 1), ('city', 2), ('date_start', 3), ('date_end', 4), ('level', 5), ('certificate', 6), ('description', 7)]], {})}, verbose_name='formation'),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='experience',
            field=wagtail.fields.StreamField([('experience_block', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'titre', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'company', 'label': 'entreprise', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'city', 'label': 'ville', 'required': True}), 3: ('wagtail.blocks.DateBlock', (), {}), 4: ('wagtail.blocks.DateBlock', (), {'required': False}), 5: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'code', 'superscript', 'subscript', 'strikethrough'], 'icon': 'pilcrow', 'required': False, 'template': 'blocks/paragraph_block.html'}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('company', 1), ('city', 2), ('date_start', 3), ('date_end', 4), ('description', 5)]], {})}, verbose_name='expérience professionnelle'),
        ),
    ]
