# Generated by Django 5.0.9 on 2024-12-21 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_resumepage_cv'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumepage',
            name='image',
        ),
        migrations.AddField(
            model_name='resumepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='hero_image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
