# Generated by Django 4.2.5 on 2023-10-04 19:25

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='date de début')),
                ('date_end', models.DateField(verbose_name='date de fin')),
                ('title', models.CharField(max_length=155, verbose_name='titre')),
                ('school', models.CharField(max_length=155, verbose_name='école')),
                ('city', models.CharField(max_length=50, verbose_name='ville')),
                ('level', models.CharField(choices=[('CAP', 'CAP'), ('BEP', 'BEP'), ('BAC', 'BAC'), ('BAC+2', 'BAC+2'), ('BAC+3', 'BAC+3'), ('BAC+4', 'BAC+4'), ('BAC+5', 'BAC+5'), ('BAC+8', 'BAC+8')], max_length=7, verbose_name='niveau')),
                ('graduation', models.BooleanField(default=False, verbose_name='diplôme obtenu')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'formation',
                'verbose_name_plural': 'formations',
                'ordering': ['-date_end'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='date de début')),
                ('date_end', models.DateField(blank=True, verbose_name='date de fin')),
                ('job', models.CharField(max_length=155, verbose_name='poste')),
                ('business', models.CharField(max_length=155, verbose_name='entreprise')),
                ('city', models.CharField(max_length=50, verbose_name='ville')),
                ('task_description', tinymce.models.HTMLField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='KnowHow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='compétence')),
            ],
            options={
                'verbose_name': 'compétence et savoir-faire',
                'verbose_name_plural': 'compétences et savoir-faire',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='compétence technique')),
                ('tag', models.CharField(choices=[('SYSTEME', 'Système'), ('BUREAUTIQUE', 'Bureautique'), ('GRAPHISME', 'Graphisme'), ('FRAMEWORK', 'Framework'), ('PROGRAMMATION', 'Programmation')], max_length=15)),
            ],
            options={
                'verbose_name': 'compétence technique',
                'verbose_name_plural': 'compétences techniques',
            },
        ),
    ]
