# Generated by Django 4.2.5 on 2023-10-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('LINKEDIN', 'Linkedin'), ('INSTAGRAM', 'Instagram'), ('CODEPEN', 'Codepen'), ('GITHUB', 'Github'), ('TWITTER', 'Twitter')], max_length=9, verbose_name='nom')),
                ('link', models.URLField(blank=True, max_length=255, verbose_name='lien')),
            ],
        ),
    ]
