# Generated by Django 4.2.5 on 2023-10-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0004_interest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': 'intérêt', 'verbose_name_plural': 'intérêts'},
        ),
    ]
