# Generated by Django 4.2.5 on 2023-10-09 21:49

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0007_auto_20231009_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'projet'},
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='image',
            field=models.ImageField(default='', upload_to='projects'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
