# Generated by Django 4.2.5 on 2023-10-09 22:19

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0008_alter_project_options_projectcategory_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategory',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='projectcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projectcategory',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='my_profile.projectcategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to='projects'),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
