# Generated by Django 4.2.5 on 2023-10-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0009_remove_projectcategory_desc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
